Fix for usage custom.css
resoai/TileBoard-addon pull request #11
Opened 2021-03-31 21:55 UTC by Romkabouter

2021-03-31 22:05 UTC, rchl requested changes

2021-03-31 22:05 UTC, rchl commented on addon/rootfs/etc/cont-init.d/tile-board.sh
> +        fi
Can you use `rm -f path` instead? Should not raise the error if the file is missing then.

2021-03-31 22:05 UTC, rchl commented on addon/config.json
> +  "version": "1.0.7",
You should not modify the version or the changelog. That is done automatically on release.

2021-03-31 22:09 UTC, rchl commented on addon/rootfs/etc/cont-init.d/tile-board.sh
> +        fi
Well, nothing wrong with the way you did it so I'll resolve it.

2021-04-01 08:58 UTC, Romkabouter commented on addon/config.json
> +  "version": "1.0.7",
ok, I have reverted this

2021-04-02 07:35 UTC, rchl commented on addon/config.json
> +  "version": "1.0.7",
There are still changes to package.json and change log

2021-04-02 07:42 UTC, Romkabouter commented on addon/config.json
> +  "version": "1.0.7",
done

2021-04-04 19:12 UTC, rchl approved these changes

2021-04-04 19:44 UTC, merged